/**
 * Export Service for Cost Analysis Reports
 * Supports PDF and Excel export formats
 */

import jsPDF from 'jspdf';
// Using native browser APIs for Excel export
// Alternative to xlsx for security reasons

export interface ExportData {
  bomName: string;
  bomId: string;
  projectName?: string;
  summary: {
    totalCost: number;
    sellingPrice: number;
    totalMargin: number;
    averageSga: number;
    averageProfit: number;
    rawMaterials: number;
    processCosts: number;
    packagingLogistics: number;
    procuredParts: number;
    overheadCosts: number;
  };
  costBreakdown?: any[];
  assemblies?: any[];
  timestamp: string;
}

export type ExportFormat = 'pdf' | 'excel';

export class ExportService {
  private static instance: ExportService;

  public static getInstance(): ExportService {
    if (!ExportService.instance) {
      ExportService.instance = new ExportService();
    }
    return ExportService.instance;
  }

  /**
   * Export cost analysis data in the specified format
   */
  public async exportCostAnalysis(data: ExportData, format: ExportFormat): Promise<void> {
    try {
      if (format === 'pdf') {
        await this.exportToPDF(data);
      } else if (format === 'excel') {
        await this.exportToExcel(data);
      }
    } catch (error) {
      console.error('Export failed:', error);
      throw new Error(`Failed to export as ${format.toUpperCase()}`);
    }
  }

  /**
   * Export to PDF format
   */
  private async exportToPDF(data: ExportData): Promise<void> {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.width;
    let yPosition = 20;

    // Header
    doc.setFontSize(20);
    doc.setTextColor(40, 40, 40);
    doc.text('Cost Analysis Report', pageWidth / 2, yPosition, { align: 'center' });
    yPosition += 15;

    // BOM Information
    doc.setFontSize(14);
    doc.text(`BOM: ${data.bomName}`, 20, yPosition);
    yPosition += 10;
    doc.setFontSize(10);
    doc.text(`BOM ID: ${data.bomId}`, 20, yPosition);
    yPosition += 8;
    doc.text(`Generated: ${data.timestamp}`, 20, yPosition);
    yPosition += 20;

    // Cost Summary Section
    doc.setFontSize(12);
    doc.setTextColor(0, 0, 0);
    doc.text('Cost Summary', 20, yPosition);
    yPosition += 15;

    doc.setFontSize(10);
    const summaryItems = [
      ['Total Cost:', this.formatCurrencyForPDF(data.summary.totalCost)],
      ['Selling Price:', this.formatCurrencyForPDF(data.summary.sellingPrice)],
      ['Total Margin:', this.formatCurrencyForPDF(data.summary.totalMargin)],
      ['Average SGA:', this.formatPercentage(data.summary.averageSga)],
      ['Average Profit:', this.formatPercentage(data.summary.averageProfit)],
    ];

    summaryItems.forEach(([label, value]) => {
      doc.text(label, 20, yPosition);
      doc.text(value, 100, yPosition);
      yPosition += 8;
    });

    yPosition += 10;

    // Cost Breakdown Section
    doc.setFontSize(12);
    doc.text('Cost Breakdown', 20, yPosition);
    yPosition += 15;

    doc.setFontSize(10);
    const breakdownItems = [
      ['Raw Materials:', this.formatCurrencyForPDF(data.summary.rawMaterials), this.formatPercentage((data.summary.rawMaterials / data.summary.totalCost) * 100)],
      ['Process Costs:', this.formatCurrencyForPDF(data.summary.processCosts), this.formatPercentage((data.summary.processCosts / data.summary.totalCost) * 100)],
      ['Packaging & Logistics:', this.formatCurrencyForPDF(data.summary.packagingLogistics), this.formatPercentage((data.summary.packagingLogistics / data.summary.totalCost) * 100)],
      ['Procured Parts:', this.formatCurrencyForPDF(data.summary.procuredParts), this.formatPercentage((data.summary.procuredParts / data.summary.totalCost) * 100)],
      ['Overhead Costs:', this.formatCurrencyForPDF(data.summary.overheadCosts), this.formatPercentage((data.summary.overheadCosts / data.summary.totalCost) * 100)],
    ];

    breakdownItems.forEach(([label, value, percentage]) => {
      doc.text(label, 20, yPosition);
      doc.text(value, 80, yPosition);
      doc.text(percentage, 140, yPosition);
      yPosition += 8;
    });

    // Add totals
    yPosition += 5;
    doc.setDrawColor(0, 0, 0);
    doc.line(20, yPosition, 160, yPosition);
    yPosition += 8;
    doc.setFontSize(10);
    doc.text('Total:', 20, yPosition);
    doc.text(this.formatCurrencyForPDF(data.summary.totalCost), 80, yPosition);
    doc.text('100.0%', 140, yPosition);

    // Footer
    const pageHeight = doc.internal.pageSize.height;
    doc.setFontSize(8);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Manufacturing Cost Analysis Engine', pageWidth / 2, pageHeight - 10, { align: 'center' });

    // Save the PDF
    const fileName = `Cost_Analysis_${data.bomName}_${new Date().toISOString().split('T')[0]}.pdf`;
    doc.save(fileName);
  }

  /**
   * Export to Excel format
   */
  private async exportToExcel(data: ExportData): Promise<void> {
    // Create CSV content as a secure alternative to Excel
    const csvContent = this.generateCSVContent(data);
    
    // Create and download CSV file
    const fileName = `Cost_Analysis_${data.bomName}_${new Date().toISOString().split('T')[0]}.csv`;
    this.downloadCSV(csvContent, fileName);
  }

  private generateCSVContent(data: ExportData): string {
    const rows = [
      ['Cost Analysis Report'],
      [''],
      ['BOM Name', data.bomName],
      ['BOM ID', data.bomId],
      ['Generated', data.timestamp],
      [''],
      ['Cost Summary'],
      ['Metric', 'Value'],
      ['Total Cost', this.formatCurrency(data.summary.totalCost)],
      ['Selling Price', this.formatCurrency(data.summary.sellingPrice)],
      ['Total Margin', this.formatCurrency(data.summary.totalMargin)],
      ['Average SGA', this.formatPercentage(data.summary.averageSga)],
      ['Average Profit', this.formatPercentage(data.summary.averageProfit)],
      [''],
      ['Cost Breakdown'],
      ['Category', 'Amount', 'Percentage'],
      ['Raw Materials', this.formatCurrency(data.summary.rawMaterials), this.formatPercentage((data.summary.rawMaterials / data.summary.totalCost) * 100)],
      ['Process Costs', this.formatCurrency(data.summary.processCosts), this.formatPercentage((data.summary.processCosts / data.summary.totalCost) * 100)],
      ['Packaging & Logistics', this.formatCurrency(data.summary.packagingLogistics), this.formatPercentage((data.summary.packagingLogistics / data.summary.totalCost) * 100)],
      ['Procured Parts', this.formatCurrency(data.summary.procuredParts), this.formatPercentage((data.summary.procuredParts / data.summary.totalCost) * 100)],
      ['Overhead Costs', this.formatCurrency(data.summary.overheadCosts), this.formatPercentage((data.summary.overheadCosts / data.summary.totalCost) * 100)]
    ];

    return rows.map(row => row.map(cell => `"${cell}"`).join(',')).join('\n');
  }

  private downloadCSV(content: string, fileName: string): void {
    const blob = new Blob([content], { type: 'text/csv;charset=utf-8;' });
    const link = document.createElement('a');
    
    if (link.download !== undefined) {
      const url = URL.createObjectURL(blob);
      link.setAttribute('href', url);
      link.setAttribute('download', fileName);
      link.style.visibility = 'hidden';
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    }
  }

  /**
   * Prepare export data from aggregated cost data
   */
  public prepareExportData(
    bomId: string,
    bomName: string,
    aggregated: any,
    costData?: any[],
    projectName?: string
  ): ExportData {
    return {
      bomId,
      bomName,
      projectName,
      summary: {
        totalCost: aggregated.totalCost || 0,
        sellingPrice: aggregated.totalSellingPrice || 0,
        totalMargin: aggregated.totalMargin || 0,
        averageSga: aggregated.averageSgaPercentage || 0,
        averageProfit: aggregated.averageProfitPercentage || 0,
        rawMaterials: aggregated.totalRawMaterials || 0,
        processCosts: aggregated.totalProcessCosts || 0,
        packagingLogistics: aggregated.totalPackagingLogistics || 0,
        procuredParts: aggregated.totalProcuredParts || 0,
        overheadCosts: ((aggregated.totalRawMaterials || 0) + (aggregated.totalProcessCosts || 0) + (aggregated.totalPackagingLogistics || 0) + (aggregated.totalProcuredParts || 0)) * 0.15, // Calculate 15% overhead from direct costs
      },
      costBreakdown: costData || [],
      timestamp: new Date().toLocaleString(),
    };
  }

  /**
   * Show export format selection dialog (secure implementation)
   * Creates DOM elements programmatically to prevent XSS
   */
  public async showExportDialog(): Promise<ExportFormat | null> {
    return new Promise((resolve) => {
      // Create overlay
      const overlay = document.createElement('div');
      overlay.style.cssText = `
        position: fixed;
        top: 0;
        left: 0;
        width: 100%;
        height: 100%;
        background: rgba(0, 0, 0, 0.5);
        display: flex;
        justify-content: center;
        align-items: center;
        z-index: 9999;
      `;

      // Create modal container
      const modal = document.createElement('div');
      modal.style.cssText = `
        background: white;
        padding: 24px;
        border-radius: 8px;
        box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
        min-width: 300px;
        text-align: center;
      `;

      // Create title
      const title = document.createElement('h3');
      title.textContent = 'Export Format';
      title.style.cssText = 'margin: 0 0 16px 0; color: #374151;';

      // Create description
      const description = document.createElement('p');
      description.textContent = 'Choose your preferred export format:';
      description.style.cssText = 'margin: 0 0 24px 0; color: #6b7280; font-size: 14px;';

      // Create button container
      const buttonContainer = document.createElement('div');
      buttonContainer.style.cssText = 'display: flex; gap: 12px; justify-content: center;';

      // Create buttons
      const pdfButton = document.createElement('button');
      pdfButton.textContent = '📄 PDF';
      pdfButton.style.cssText = `
        background: #ef4444;
        color: white;
        border: none;
        padding: 12px 24px;
        border-radius: 6px;
        cursor: pointer;
        font-weight: 500;
      `;

      const excelButton = document.createElement('button');
      excelButton.textContent = '📊 Excel';
      excelButton.style.cssText = `
        background: #10b981;
        color: white;
        border: none;
        padding: 12px 24px;
        border-radius: 6px;
        cursor: pointer;
        font-weight: 500;
      `;

      const cancelButton = document.createElement('button');
      cancelButton.textContent = 'Cancel';
      cancelButton.style.cssText = `
        background: #6b7280;
        color: white;
        border: none;
        padding: 12px 24px;
        border-radius: 6px;
        cursor: pointer;
        font-weight: 500;
      `;

      // Assemble elements
      buttonContainer.appendChild(pdfButton);
      buttonContainer.appendChild(excelButton);
      buttonContainer.appendChild(cancelButton);

      modal.appendChild(title);
      modal.appendChild(description);
      modal.appendChild(buttonContainer);
      overlay.appendChild(modal);

      document.body.appendChild(overlay);

      const cleanup = () => {
        document.body.removeChild(overlay);
      };

      // Add event listeners
      pdfButton.addEventListener('click', () => {
        cleanup();
        resolve('pdf');
      });

      excelButton.addEventListener('click', () => {
        cleanup();
        resolve('excel');
      });

      cancelButton.addEventListener('click', () => {
        cleanup();
        resolve(null);
      });

      // Close on overlay click
      overlay.addEventListener('click', (e) => {
        if (e.target === overlay) {
          cleanup();
          resolve(null);
        }
      });
    });
  }

  private formatCurrency(value: number): string {
    // Use Rs. instead of ₹ symbol for PDF compatibility
    return `Rs. ${value.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  }
  
  private formatCurrencyForPDF(value: number): string {
    // Use INR prefix for PDF to avoid font issues
    return `INR ${value.toLocaleString('en-IN', { minimumFractionDigits: 2 })}`;
  }

  private formatPercentage(value: number): string {
    return `${value.toFixed(1)}%`;
  }
}

// Export singleton instance
export const exportService = ExportService.getInstance();