-- VAVE (Value Analysis / Value Engineering) Module Schema
-- Migration 312: Create vave_projects, vave_bom, vave_ideas, vave_should_costs

-- VAVE Projects
CREATE TABLE IF NOT EXISTS vave_projects (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name            VARCHAR NOT NULL,
  product_family  VARCHAR,
  description     TEXT,
  status          VARCHAR NOT NULL DEFAULT 'phase1',
  owner_id        UUID REFERENCES auth.users(id),
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- BOM items imported/linked for VAVE analysis
CREATE TABLE IF NOT EXISTS vave_bom (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id       UUID NOT NULL REFERENCES vave_projects(id) ON DELETE CASCADE,
  part_number      VARCHAR NOT NULL,
  description      VARCHAR,
  level            INTEGER NOT NULL DEFAULT 1,
  parent_pn        VARCHAR,
  quantity         DECIMAL NOT NULL DEFAULT 1,
  unit_cost        DECIMAL NOT NULL DEFAULT 0,
  annual_volume    INTEGER NOT NULL DEFAULT 0,
  annual_spend     DECIMAL GENERATED ALWAYS AS (unit_cost * annual_volume) STORED,
  material         VARCHAR,
  process          VARCHAR,
  supplier_name    VARCHAR,
  drawing_url      TEXT,
  model_url        TEXT,
  drawing_analysis JSONB,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- VAVE ideas generated by AI (SCAMPER/TRIZ/FAST) or entered manually
CREATE TABLE IF NOT EXISTS vave_ideas (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id               UUID NOT NULL REFERENCES vave_projects(id) ON DELETE CASCADE,
  title                    VARCHAR NOT NULL,
  description              TEXT,
  framework                VARCHAR NOT NULL DEFAULT 'Manual',
  scamper_type             VARCHAR,
  affected_parts           JSONB NOT NULL DEFAULT '[]',
  est_savings_usd          DECIMAL NOT NULL DEFAULT 0,
  est_investment_usd       DECIMAL NOT NULL DEFAULT 0,
  feasibility              VARCHAR NOT NULL DEFAULT 'Medium',
  complexity               VARCHAR NOT NULL DEFAULT 'L2',
  risk                     VARCHAR NOT NULL DEFAULT 'Medium',
  quadrant                 VARCHAR,
  status                   VARCHAR NOT NULL DEFAULT 'draft',
  time_to_implement_months INTEGER,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Should-cost records — actual vs AI-estimated should cost per part
CREATE TABLE IF NOT EXISTS vave_should_costs (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  project_id       UUID NOT NULL REFERENCES vave_projects(id) ON DELETE CASCADE,
  part_number      VARCHAR NOT NULL,
  description      VARCHAR,
  actual_cost      DECIMAL NOT NULL DEFAULT 0,
  should_cost      DECIMAL NOT NULL DEFAULT 0,
  delta            DECIMAL GENERATED ALWAYS AS (actual_cost - should_cost) STORED,
  delta_pct        DECIMAL,
  material_cost    DECIMAL,
  process_cost     DECIMAL,
  overhead         DECIMAL,
  margin           DECIMAL,
  benchmark_source VARCHAR,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_vave_bom_project_id ON vave_bom(project_id);
CREATE INDEX IF NOT EXISTS idx_vave_ideas_project_id ON vave_ideas(project_id);
CREATE INDEX IF NOT EXISTS idx_vave_ideas_status ON vave_ideas(status);
CREATE INDEX IF NOT EXISTS idx_vave_should_costs_project_id ON vave_should_costs(project_id);

-- Row Level Security
ALTER TABLE vave_projects    ENABLE ROW LEVEL SECURITY;
ALTER TABLE vave_bom         ENABLE ROW LEVEL SECURITY;
ALTER TABLE vave_ideas       ENABLE ROW LEVEL SECURITY;
ALTER TABLE vave_should_costs ENABLE ROW LEVEL SECURITY;

-- Project access: owner only (or no owner for dev/migration seeds)
CREATE POLICY "vave_projects_select" ON vave_projects
  FOR SELECT USING (auth.uid() = owner_id OR owner_id IS NULL);
CREATE POLICY "vave_projects_insert" ON vave_projects
  FOR INSERT WITH CHECK (auth.uid() = owner_id OR owner_id IS NULL);
CREATE POLICY "vave_projects_update" ON vave_projects
  FOR UPDATE USING (auth.uid() = owner_id OR owner_id IS NULL);
CREATE POLICY "vave_projects_delete" ON vave_projects
  FOR DELETE USING (auth.uid() = owner_id OR owner_id IS NULL);

-- Sub-table access: inherited from project ownership
CREATE POLICY "vave_bom_all" ON vave_bom FOR ALL
  USING (EXISTS (
    SELECT 1 FROM vave_projects p
    WHERE p.id = project_id AND (p.owner_id = auth.uid() OR p.owner_id IS NULL)
  ));

CREATE POLICY "vave_ideas_all" ON vave_ideas FOR ALL
  USING (EXISTS (
    SELECT 1 FROM vave_projects p
    WHERE p.id = project_id AND (p.owner_id = auth.uid() OR p.owner_id IS NULL)
  ));

CREATE POLICY "vave_should_costs_all" ON vave_should_costs FOR ALL
  USING (EXISTS (
    SELECT 1 FROM vave_projects p
    WHERE p.id = project_id AND (p.owner_id = auth.uid() OR p.owner_id IS NULL)
  ));

-- updated_at triggers (reuse existing function if present, else create)
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_proc WHERE proname = 'update_updated_at_column') THEN
    CREATE OR REPLACE FUNCTION update_updated_at_column()
    RETURNS TRIGGER AS $func$
    BEGIN NEW.updated_at = NOW(); RETURN NEW; END;
    $func$ LANGUAGE plpgsql;
  END IF;
END$$;

CREATE TRIGGER update_vave_projects_updated_at
  BEFORE UPDATE ON vave_projects
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_vave_ideas_updated_at
  BEFORE UPDATE ON vave_ideas
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
