-- ================================================================
-- Migration 013: Populate Quality Approved Items
-- Issue: No quality-approved items showing in delivery order creation
-- Solution: Create sample quality approved items from existing BOM items
-- ================================================================

BEGIN;

-- First, delete delivery items that reference quality_approved_items we want to clean up
DELETE FROM delivery_items 
WHERE quality_approved_item_id IN (
    SELECT id FROM quality_approved_items WHERE created_by = 'system'
);

-- Then delete any existing sample data
DELETE FROM quality_approved_items WHERE created_by = 'system';

-- Populate quality_approved_items with sample data based on existing BOM items
-- This creates approved items that will show up in the delivery order creation
INSERT INTO quality_approved_items (
    bom_item_id,
    approved_quantity,
    approval_status,
    delivery_ready,
    qc_certificate_number,
    certificate_date,
    quality_grade,
    batch_number,
    actual_weight_kg,
    approved_unit_cost_inr,
    approved_by,
    approved_at,
    delivery_ready_date,
    storage_location,
    created_by,
    updated_by,
    created_at,
    updated_at
)
SELECT 
    bi.id,
    CASE 
        WHEN bi.quantity IS NOT NULL AND bi.quantity > 0 THEN LEAST(bi.quantity, 10)
        ELSE 5
    END as approved_quantity,
    'approved' as approval_status,
    true as delivery_ready,
    NULL as qc_certificate_number, -- Will be auto-generated by trigger
    CURRENT_DATE as certificate_date,
    'A' as quality_grade,
    'BATCH-' || TO_CHAR(NOW(), 'YYYYMM') || '-' || LPAD((ROW_NUMBER() OVER ())::text, 3, '0') as batch_number,
    CASE 
        WHEN bi.material ILIKE '%steel%' THEN 2.5
        WHEN bi.material ILIKE '%aluminum%' THEN 1.2
        WHEN bi.material ILIKE '%plastic%' THEN 0.8
        ELSE 1.5
    END as actual_weight_kg,
    COALESCE(bi.unit_cost_inr, 100) as approved_unit_cost_inr,
    'quality-inspector' as approved_by,
    NOW() - INTERVAL '1 day' as approved_at,
    NOW() as delivery_ready_date,
    'Warehouse-A-' || (1 + (ROW_NUMBER() OVER ()) % 5) as storage_location,
    'system' as created_by,
    'system' as updated_by,
    NOW() - INTERVAL '2 days' as created_at,
    NOW() - INTERVAL '1 day' as updated_at
FROM bom_items bi
JOIN boms b ON bi.bom_id = b.id
JOIN projects p ON b.project_id = p.id
WHERE bi.id IS NOT NULL
  AND bi.part_number IS NOT NULL
  AND bi.description IS NOT NULL
  -- Only create for the first 15 items to avoid too much sample data
  AND bi.id IN (
    SELECT id FROM bom_items 
    ORDER BY created_at DESC 
    LIMIT 15
  );

-- Update the delivery_ready status to ensure consistency
UPDATE quality_approved_items 
SET 
    delivery_ready = true,
    delivery_ready_date = COALESCE(delivery_ready_date, NOW())
WHERE approval_status = 'approved' AND delivery_ready = false;

-- Add some additional sample items with different statuses for testing
INSERT INTO quality_approved_items (
    bom_item_id,
    approved_quantity,
    approval_status,
    delivery_ready,
    quality_grade,
    batch_number,
    approved_by,
    approved_at,
    created_by,
    updated_by
)
SELECT 
    bi.id,
    3 as approved_quantity,
    'conditionally_approved' as approval_status,
    false as delivery_ready,
    'B' as quality_grade,
    'BATCH-COND-' || LPAD((ROW_NUMBER() OVER ())::text, 3, '0') as batch_number,
    'quality-inspector' as approved_by,
    NOW() - INTERVAL '6 hours' as approved_at,
    'system' as created_by,
    'system' as updated_by
FROM bom_items bi
JOIN boms b ON bi.bom_id = b.id
JOIN projects p ON b.project_id = p.id
WHERE bi.id IS NOT NULL
  AND bi.part_number IS NOT NULL
  AND bi.description IS NOT NULL
  -- Get different items for conditional approval
  AND bi.id IN (
    SELECT id FROM bom_items 
    WHERE id NOT IN (SELECT bom_item_id FROM quality_approved_items)
    ORDER BY created_at DESC 
    LIMIT 5
  );

-- Verify data was created
DO $$
DECLARE
    approved_count INTEGER;
    delivery_ready_count INTEGER;
    project_count INTEGER;
BEGIN
    -- Count approved items
    SELECT COUNT(*) INTO approved_count
    FROM quality_approved_items 
    WHERE approval_status = 'approved';
    
    -- Count delivery ready items
    SELECT COUNT(*) INTO delivery_ready_count
    FROM quality_approved_items 
    WHERE delivery_ready = true;
    
    -- Count projects with approved items
    SELECT COUNT(DISTINCT b.project_id) INTO project_count
    FROM quality_approved_items qai
    JOIN bom_items bi ON qai.bom_item_id = bi.id
    JOIN boms b ON bi.bom_id = b.id;
    
    RAISE NOTICE 'Created % approved items, % delivery ready items across % projects', 
        approved_count, delivery_ready_count, project_count;
        
    IF approved_count = 0 THEN
        RAISE EXCEPTION 'Failed to create any approved items. Check if BOM items exist.';
    END IF;
    
    IF delivery_ready_count = 0 THEN
        RAISE EXCEPTION 'No delivery ready items created. Check delivery readiness logic.';
    END IF;
END $$;

-- Refresh materialized view if it exists
DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_matviews WHERE matviewname = 'delivery_quality_metrics') THEN
        REFRESH MATERIALIZED VIEW delivery_quality_metrics;
        RAISE NOTICE 'Refreshed delivery_quality_metrics materialized view';
    END IF;
EXCEPTION 
    WHEN OTHERS THEN
        RAISE NOTICE 'Could not refresh materialized view: %', SQLERRM;
END $$;

-- Grant permissions to ensure access
GRANT SELECT ON quality_approved_items TO authenticated;
GRANT SELECT ON delivery_ready_items TO authenticated;

-- Add debugging query
COMMENT ON TABLE quality_approved_items IS 'Bridge table between quality inspections and delivery - populated with sample data for testing delivery order creation';

COMMIT;